spring.application.name=transaction-service

# DATABASE CONFIGURATION

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/transaction_db?createDatabaseIfNotExist=true}
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE CONFIGURATION

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# KAFKA CONFIGURATION

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Kafka Consumer

spring.kafka.consumer.group-id=transaction-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=java.util.HashMap


# Kafka Producer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# SERVER CONFIGURATION

server.port=8082
public.api.base-url=${PUBLIC_API_BASE_URL:http://localhost:8080}

# Redis Config

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379

# ACCOUNT SERVICE CONFIGURATION

account.service.url=${ACCOUNT_SERVICE_URL:http://localhost:8081}

# ACTUATOR CONFIGURATION

management.endpoints.web.exposure.include=health,info
