
spring.application.name=fraud-detection-service

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.group-id=fraud-detection-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=java.util.HashMap

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

server.port=8084

# Account Service URL for Feign Client
account.service.url=${ACCOUNT_SERVICE_URL:http://localhost:8081}

fraud.max-transactions-per-minute=5
fraud.suspicious-amount-multiplier=5
fraud.max-balance-percentage=0.90

management.endpoints.web.exposure.include=health,info
